appEnv: development

database:
  user: root
  password: root
  net: tcp
  addr: 127.0.0.1:3306
  dbname: planet-ent-example
  allowNativePasswords: true
  params:
    parseTime: true
    charset: utf8mb4
    loc: Asia/Tokyo
